language: node_js
node_js:
- 8.11.1
env:
  matrix:
  - DEBUG="retry2" DEBUG_COLORS=1
install:
- yarn install
- yarn run build
script:
- yarn run test:coverage
after_success: yarn run coverage
deploy:
  provider: npm
  email: renoth@wildoak.de
  api_key:
    secure: BJ+5Q2B7XNYS3vek3IqPXqkJT3QKRc97rmUjplP5u/lofsqo1SuOSFNQ+7jJ3OgyEWjT6V13FBmSFAuTPGHsnjR2DsWh5cYhWrk++AfKDFnR9rNxHT362mbK4BLgc4XAA6zImPMoq1hS5yrI9HMcPbNktJhOVdWDeMPXNf1hnRl4TTBhccT0xNo1eElNXb+yzJ9by7vNFgsZ3HWyL5iAXGb/zKz2vqsKi2fumVDJ2/BwvLEBFRLd+33l4mDaQqtcJlkT5qcVCRAOWGsZcco8/W6RsIyiVKI8KrgconWM1i/FCzQul1AfqEmb2sRlZYUqJC6lW+Smp9Jvwf10sJtvORrCHi3ZqnQFTUgKVFZHAs5lMzK99jtym59o2mYbqo3li3sZ8H/LtJYDvXipp0FMaD4pwjaZkQlqFrLNLIw3z1UK9cuKvKetZw/E3Xd3LCqp4VMTF1ITWnkFCYhRgKhsYcwskK+wY23SY5eSGuhWk99X8kb7idE+mwyDZx4K0zv5hQ/RwkXUrC0hEfvce0cRteGpM0OWYcAafMFRAk/qWC6mDzdPA9y1AyVZ+FTMUHuvVsTej77oCDcJgXvWAISLDTbCrlGunhQdLzHA9ucD+zcNBJoPl0PeLFMlY5rwYBy3dLJDwn8cNihZsA2a2ZX+0qmfJiiqVnlZzo087LsRvPU=
  on:
    tags: true
